import { DBModel, Table, Column, Index, Relation, DatabaseType } from '@/types';

export function generateDDL(model: DBModel): string {
  const lines: string[] = [];
  lines.push(`-- Generated by DBDesigner Pro`);
  lines.push(`-- Database Type: ${model.databaseType.toUpperCase()}`);
  lines.push(`-- Tables: ${model.tables.length}`);
  lines.push('');

  for (const table of model.tables) {
    lines.push(...generateTableDDL(table, model.databaseType));
    lines.push('');
  }

  for (const relation of model.relations) {
    lines.push(...generateRelationDDL(relation, model));
    lines.push('');
  }

  return lines.join('\n');
}

function generateTableDDL(table: Table, dbType: DatabaseType): string[] {
  const lines: string[] = [];

  if (table.comment) {
    lines.push(`-- ${table.name}: ${table.comment}`);
  }

  let createLine = `CREATE TABLE ${escapeIdentifier(table.name, dbType)} (`;
  lines.push(createLine);

  const columnLines: string[] = [];
  for (const col of table.columns.sort((a, b) => a.ordinal - b.ordinal)) {
    columnLines.push('  ' + generateColumnDef(col, dbType));
  }

  // Primary key
  const pkColumns = table.columns.filter(c => c.isPrimaryKey).sort((a, b) => a.ordinal - b.ordinal);
  if (pkColumns.length > 0) {
    const pkName = table.indexes.find(i => i.type === 'primary')?.name || `pk_${table.name}`;
    columnLines.push(`  CONSTRAINT ${escapeIdentifier(pkName, dbType)} PRIMARY KEY (${pkColumns.map(c => escapeIdentifier(c.name, dbType)).join(', ')})`);
  }

  // Unique constraints
  for (const idx of table.indexes.filter(i => i.type === 'unique')) {
    const cols = idx.columns.map(ic => {
      const col = table.columns.find(c => c.id === ic.columnId);
      return col ? escapeIdentifier(col.name, dbType) : '';
    }).filter(Boolean);
    if (cols.length > 0) {
      columnLines.push(`  CONSTRAINT ${escapeIdentifier(idx.name, dbType)} UNIQUE (${cols.join(', ')})`);
    }
  }

  lines.push(columnLines.join(',\n'));

  let closeLine = ')';
  if (dbType === 'mysql') {
    if (table.engine) closeLine += ` ENGINE=${table.engine}`;
    if (table.charset) closeLine += ` DEFAULT CHARSET=${table.charset}`;
  }
  closeLine += ';';
  lines.push(closeLine);

  // Table comment
  if (table.comment && dbType === 'mysql') {
    lines.push(`ALTER TABLE ${escapeIdentifier(table.name, dbType)} COMMENT = '${escapeString(table.comment)}';`);
  }

  // Column comments
  for (const col of table.columns) {
    if (col.comment) {
      if (dbType === 'mysql') {
        lines.push(`ALTER TABLE ${escapeIdentifier(table.name, dbType)} MODIFY COLUMN ${generateColumnDef(col, dbType)} COMMENT '${escapeString(col.comment)}';`);
      } else if (dbType === 'dm') {
        lines.push(`COMMENT ON COLUMN ${escapeIdentifier(table.name, dbType)}.${escapeIdentifier(col.name, dbType)} IS '${escapeString(col.comment)}';`);
      }
    }
  }

  // Indexes
  for (const idx of table.indexes.filter(i => i.type === 'index' || i.type === 'fulltext')) {
    const cols = idx.columns.map(ic => {
      const col = table.columns.find(c => c.id === ic.columnId);
      return col ? escapeIdentifier(col.name, dbType) : '';
    }).filter(Boolean);
    if (cols.length > 0) {
      let idxType = '';
      if (idx.type === 'fulltext') idxType = 'FULLTEXT ';
      if (idx.method) idxType += `${idx.method.toUpperCase()} `;
      lines.push(`CREATE ${idxType}INDEX ${escapeIdentifier(idx.name, dbType)} ON ${escapeIdentifier(table.name, dbType)} (${cols.join(', ')});`);
    }
  }

  return lines;
}

function generateColumnDef(col: Column, dbType: DatabaseType): string {
  let def = escapeIdentifier(col.name, dbType) + ' ';
  def += col.dataType;

  const typeInfo = getTypeInfo(col.dataType, dbType);
  if (typeInfo?.hasLength && col.length !== undefined) {
    if (typeInfo.hasPrecision && col.precision !== undefined) {
      def += `(${col.length}, ${col.precision})`;
    } else {
      def += `(${col.length})`;
    }
  }

  if (!col.nullable) {
    def += ' NOT NULL';
  }

  if (col.autoIncrement && dbType === 'mysql') {
    def += ' AUTO_INCREMENT';
  }

  if (col.defaultValue !== undefined && col.defaultValue !== '') {
    def += ` DEFAULT ${col.defaultValue}`;
  }

  return def;
}

function generateRelationDDL(relation: Relation, model: DBModel): string[] {
  const fromTable = model.tables.find(t => t.id === relation.fromTableId);
  const toTable = model.tables.find(t => t.id === relation.toTableId);
  const fromCol = fromTable?.columns.find(c => c.id === relation.fromColumnId);
  const toCol = toTable?.columns.find(c => c.id === relation.toColumnId);

  if (!fromTable || !toTable || !fromCol || !toCol) return [];

  const lines: string[] = [];
  const fkName = `fk_${fromTable.name}_${fromCol.name}_${toTable.name}`;

  lines.push(`ALTER TABLE ${escapeIdentifier(fromTable.name, model.databaseType)}`);
  lines.push(`  ADD CONSTRAINT ${escapeIdentifier(fkName, model.databaseType)}`);
  lines.push(`  FOREIGN KEY (${escapeIdentifier(fromCol.name, model.databaseType)})`);
  lines.push(`  REFERENCES ${escapeIdentifier(toTable.name, model.databaseType)} (${escapeIdentifier(toCol.name, model.databaseType)})`);
  lines.push(`  ON UPDATE ${relation.onUpdate.toUpperCase().replace('_', ' ')}`);
  lines.push(`  ON DELETE ${relation.onDelete.toUpperCase().replace('_', ' ')};`);

  return lines;
}

function escapeIdentifier(name: string, dbType: DatabaseType): string {
  if (dbType === 'mysql') return `\`${name}\``;
  return `"${name}"`;
}

function escapeString(str: string): string {
  return str.replace(/'/g, "''");
}

function getTypeInfo(dataType: string, dbType: DatabaseType): { hasLength: boolean; hasPrecision: boolean } | null {
  const types: Record<string, { hasLength: boolean; hasPrecision: boolean }> = {
    'TINYINT': { hasLength: true, hasPrecision: false },
    'SMALLINT': { hasLength: true, hasPrecision: false },
    'MEDIUMINT': { hasLength: true, hasPrecision: false },
    'INT': { hasLength: true, hasPrecision: false },
    'BIGINT': { hasLength: true, hasPrecision: false },
    'FLOAT': { hasLength: true, hasPrecision: true },
    'DOUBLE': { hasLength: true, hasPrecision: true },
    'DECIMAL': { hasLength: true, hasPrecision: true },
    'NUMERIC': { hasLength: true, hasPrecision: true },
    'NUMBER': { hasLength: true, hasPrecision: true },
    'CHAR': { hasLength: true, hasPrecision: false },
    'CHARACTER': { hasLength: true, hasPrecision: false },
    'VARCHAR': { hasLength: true, hasPrecision: false },
    'VARCHAR2': { hasLength: true, hasPrecision: false },
    'BINARY': { hasLength: true, hasPrecision: false },
    'VARBINARY': { hasLength: true, hasPrecision: false },
    'BIT': { hasLength: true, hasPrecision: false },
    'VARBIT': { hasLength: true, hasPrecision: false },
  };
  return types[dataType] || null;
}
