import { DBModel, Table, Column, Index, Relation, DatabaseType } from '@/types';

export function generateDDL(model: DBModel): string {
  const lines: string[] = [];
  lines.push(`-- Generated by DBDesigner Pro`);
  lines.push(`-- Database Type: ${model.databaseType.toUpperCase()}`);
  lines.push(`-- Tables: ${model.tables.length}`);
  lines.push('');

  for (const table of model.tables) {
    lines.push(...generateTableDDL(table, model.databaseType));
    lines.push('');
  }

  for (const relation of model.relations) {
    lines.push(...generateRelationDDL(relation, model));
    lines.push('');
  }

  return lines.join('\n');
}

function generateTableDDL(table: Table, dbType: DatabaseType): string[] {
  const lines: string[] = [];

  if (table.comment) {
    lines.push(`-- ${table.name}: ${table.comment}`);
  }

  let createLine = `CREATE TABLE ${escapeIdentifier(table.name, dbType)} (`;
  lines.push(createLine);

  const columnLines: string[] = [];
  for (const col of table.columns.sort((a, b) => a.ordinal - b.ordinal)) {
    columnLines.push('  ' + generateColumnDef(col, dbType));
  }

  // Primary key
  const pkColumns = table.columns.filter(c => c.isPrimaryKey).sort((a, b) => a.ordinal - b.ordinal);
  if (pkColumns.length > 0) {
    const pkName = table.indexes.find(i => i.type === 'primary')?.name || `pk_${table.name}`;
    columnLines.push(`  CONSTRAINT ${escapeIdentifier(pkName, dbType)} PRIMARY KEY (${pkColumns.map(c => escapeIdentifier(c.name, dbType)).join(', ')})`);
  }

  // Unique constraints
  for (const idx of table.indexes.filter(i => i.type === 'unique')) {
    const cols = idx.columns.map(ic => {
      const col = table.columns.find(c => c.id === ic.columnId);
      return col ? escapeIdentifier(col.name, dbType) : '';
    }).filter(Boolean);
    if (cols.length > 0) {
      columnLines.push(`  CONSTRAINT ${escapeIdentifier(idx.name, dbType)} UNIQUE (${cols.join(', ')})`);
    }
  }

  lines.push(columnLines.join(',\n'));

  let closeLine = ')';
  if (dbType === 'mysql') {
    if (table.engine) closeLine += ` ENGINE=${table.engine}`;
    if (table.charset) closeLine += ` DEFAULT CHARSET=${table.charset}`;
  }
  closeLine += ';';
  lines.push(closeLine);

  // Table comment
  if (table.comment && dbType === 'mysql') {
    lines.push(`ALTER TABLE ${escapeIdentifier(table.name, dbType)} COMMENT = '${escapeString(table.comment)}';`);
  }

  // Column comments
  for (const col of table.columns) {
    if (col.comment) {
      if (dbType === 'mysql') {
        lines.push(`ALTER TABLE ${escapeIdentifier(table.name, dbType)} MODIFY COLUMN ${generateColumnDef(col, dbType)} COMMENT '${escapeString(col.comment)}';`);
      } else if (dbType === 'dm') {
        lines.push(`COMMENT ON COLUMN ${escapeIdentifier(table.name, dbType)}.${escapeIdentifier(col.name, dbType)} IS '${escapeString(col.comment)}';`);
      }
    }
  }

  // Indexes
  for (const idx of table.indexes.filter(i => i.type === 'index' || i.type === 'fulltext')) {
    const cols = idx.columns.map(ic => {
      const col = table.columns.find(c => c.id === ic.columnId);
      return col ? escapeIdentifier(col.name, dbType) : '';
    }).filter(Boolean);
    if (cols.length > 0) {
      let idxType = '';
      if (idx.type === 'fulltext') idxType = 'FULLTEXT ';
      if (idx.method) idxType += `${idx.method.toUpperCase()} `;
      lines.push(`CREATE ${idxType}INDEX ${escapeIdentifier(idx.name, dbType)} ON ${escapeIdentifier(table.name, dbType)} (${cols.join(', ')});`);
    }
  }

  return lines;
}

function generateColumnDef(col: Column, dbType: DatabaseType): string {
  let def = escapeIdentifier(col.name, dbType) + ' ';
  def += col.dataType;

  const typeInfo = getTypeInfo(col.dataType, dbType);
  if (typeInfo?.hasLength && col.length !== undefined) {
    if (typeInfo.hasPrecision && col.precision !== undefined) {
      def += `(${col.length}, ${col.precision})`;
    } else {
      def += `(${col.length})`;
    }
  }

  if (!col.nullable) {
    def += ' NOT NULL';
  }

  if (col.autoIncrement && dbType === 'mysql') {
    def += ' AUTO_INCREMENT';
  }

  if (col.defaultValue !== undefined && col.defaultValue !== '') {
    def += ` DEFAULT ${col.defaultValue}`;
  }

  return def;
}

function generateRelationDDL(relation: Relation, model: DBModel): string[] {
  const fromTable = model.tables.find(t => t.id === relation.fromTableId);
  const toTable = model.tables.find(t => t.id === relation.toTableId);
  const fromCol = fromTable?.columns.find(c => c.id === relation.fromColumnId);
  const toCol = toTable?.columns.find(c => c.id === relation.toColumnId);

  if (!fromTable || !toTable || !fromCol || !toCol) return [];

  const lines: string[] = [];
  const fkName = `fk_${fromTable.name}_${fromCol.name}_${toTable.name}`;

  lines.push(`ALTER TABLE ${escapeIdentifier(fromTable.name, model.databaseType)}`);
  lines.push(`  ADD CONSTRAINT ${escapeIdentifier(fkName, model.databaseType)}`);
  lines.push(`  FOREIGN KEY (${escapeIdentifier(fromCol.name, model.databaseType)})`);
  lines.push(`  REFERENCES ${escapeIdentifier(toTable.name, model.databaseType)} (${escapeIdentifier(toCol.name, model.databaseType)})`);
  lines.push(`  ON UPDATE ${relation.onUpdate.toUpperCase().replace('_', ' ')}`);
  lines.push(`  ON DELETE ${relation.onDelete.toUpperCase().replace('_', ' ')};`);

  return lines;
}

function escapeIdentifier(name: string, dbType: DatabaseType): string {
  if (dbType === 'mysql') return `\`${name}\``;
  return `"${name}"`;
}

function escapeString(str: string): string {
  return str.replace(/'/g, "''");
}

function getTypeInfo(dataType: string, dbType: DatabaseType): { hasLength: boolean; hasPrecision: boolean } | null {
  const types: Record<string, { hasLength: boolean; hasPrecision: boolean }> = {
    'TINYINT': { hasLength: true, hasPrecision: false },
    'SMALLINT': { hasLength: true, hasPrecision: false },
    'MEDIUMINT': { hasLength: true, hasPrecision: false },
    'INT': { hasLength: true, hasPrecision: false },
    'BIGINT': { hasLength: true, hasPrecision: false },
    'FLOAT': { hasLength: true, hasPrecision: true },
    'DOUBLE': { hasLength: true, hasPrecision: true },
    'DECIMAL': { hasLength: true, hasPrecision: true },
    'NUMERIC': { hasLength: true, hasPrecision: true },
    'NUMBER': { hasLength: true, hasPrecision: true },
    'CHAR': { hasLength: true, hasPrecision: false },
    'CHARACTER': { hasLength: true, hasPrecision: false },
    'VARCHAR': { hasLength: true, hasPrecision: false },
    'VARCHAR2': { hasLength: true, hasPrecision: false },
    'BINARY': { hasLength: true, hasPrecision: false },
    'VARBINARY': { hasLength: true, hasPrecision: false },
    'BIT': { hasLength: true, hasPrecision: false },
    'VARBIT': { hasLength: true, hasPrecision: false },
  };
  return types[dataType] || null;
}

export function generateDataDictionary(model: DBModel): string {
  const html = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <title>数据字典 - ${model.databaseType.toUpperCase()}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 0; padding: 20px; background: #f8fafc; color: #1e293b; }
    h1 { text-align: center; color: #0f172a; margin-bottom: 8px; }
    .subtitle { text-align: center; color: #64748b; margin-bottom: 32px; }
    .table-section { background: white; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 24px; overflow: hidden; }
    .table-header { background: #0ea5e9; color: white; padding: 16px 20px; }
    .table-header h2 { margin: 0; font-size: 18px; }
    .table-header .comment { opacity: 0.9; font-size: 14px; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 12px 16px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f1f5f9; font-weight: 600; font-size: 13px; color: #475569; }
    td { font-size: 14px; }
    .pk { color: #dc2626; font-weight: bold; }
    .fk { color: #2563eb; }
    .nullable { color: #94a3b8; }
    .index-section { padding: 16px 20px; background: #f8fafc; }
    .index-section h3 { margin: 0 0 12px 0; font-size: 14px; color: #475569; }
    .index-tag { display: inline-block; background: #e0f2fe; color: #0369a1; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-right: 8px; }
  </style>
</head>
<body>
  <h1>数据字典</h1>
  <div class="subtitle">数据库类型: ${model.databaseType.toUpperCase()} | 表数量: ${model.tables.length}</div>
  ${model.tables.map(table => generateTableDict(table, model)).join('')}
</body>
</html>`;
  return html;
}

function generateTableDict(table: Table, model: DBModel): string {
  const relatedRelations = model.relations.filter(r => r.fromTableId === table.id || r.toTableId === table.id);

  return `
  <div class="table-section">
    <div class="table-header">
      <h2>${table.name}</h2>
      ${table.comment ? `<div class="comment">${table.comment}</div>` : ''}
    </div>
    <table>
      <thead>
        <tr>
          <th>序号</th>
          <th>字段名</th>
          <th>数据类型</th>
          <th>可空</th>
          <th>默认值</th>
          <th>约束</th>
          <th>注释</th>
        </tr>
      </thead>
      <tbody>
        ${table.columns.sort((a, b) => a.ordinal - b.ordinal).map((col, idx) => {
          const constraints: string[] = [];
          if (col.isPrimaryKey) constraints.push('<span class="pk">PK</span>');
          if (col.isUnique) constraints.push('<span class="fk">UK</span>');
          if (col.autoIncrement) constraints.push('AI');

          const fkRel = relatedRelations.find(r => r.fromColumnId === col.id);
          if (fkRel) {
            const toTable = model.tables.find(t => t.id === fkRel.toTableId);
            const toCol = toTable?.columns.find(c => c.id === fkRel.toColumnId);
            if (toTable && toCol) {
              constraints.push(`<span class="fk">FK → ${toTable.name}.${toCol.name}</span>`);
            }
          }

          let typeStr = col.dataType;
          const typeInfo = getTypeInfo(col.dataType, model.databaseType);
          if (typeInfo?.hasLength && col.length !== undefined) {
            if (typeInfo.hasPrecision && col.precision !== undefined) {
              typeStr += `(${col.length},${col.precision})`;
            } else {
              typeStr += `(${col.length})`;
            }
          }

          return `<tr>
            <td>${idx + 1}</td>
            <td><strong>${col.name}</strong></td>
            <td>${typeStr}</td>
            <td>${col.nullable ? '<span class="nullable">YES</span>' : 'NO'}</td>
            <td>${col.defaultValue || ''}</td>
            <td>${constraints.join(' ')}</td>
            <td>${col.comment || ''}</td>
          </tr>`;
        }).join('')}
      </tbody>
    </table>
    ${table.indexes.length > 0 ? `
    <div class="index-section">
      <h3>索引</h3>
      ${table.indexes.map(idx => {
        const cols = idx.columns.map(ic => {
          const col = table.columns.find(c => c.id === ic.columnId);
          return col ? col.name : '';
        }).filter(Boolean).join(', ');
        return `<span class="index-tag">${idx.name} (${idx.type}${idx.method ? `, ${idx.method}` : ''}): ${cols}</span>`;
      }).join('')}
    </div>
    ` : ''}
  </div>`;
}
